channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.7.6
  - conda-forge::biopython=1.76
  - conda-forge::matplotlib=3.1.2
  - conda-forge::numba=0.47.0
  - conda-forge::numpy=1.17.5
  - conda-forge::scipy=1.4.1